config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users, only: [:new, :create, :show] do
    resources :items, only: [:create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  before_save { self.email = email.downcase }
  validates :name, length: { minimum: 1, maximum: 100 }, presence: true
  validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 254 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
   @user = User.find(params[:user_id])
   @item = Item.new
  end

  def create
     @item = Item.new
     @item.name = params[:item][:name]
     @user = User.find(params[:user_id])
     @item.user = @user

     if @item.save
       flash[:notice] = "Item was saved."
       redirect_to user_path(current_user)
     else
       flash.now[:alert] = "There was an error saving the item. Please try again."
       render :new
     end
   end

   def edit
     @item = Item.find(params[:id])
   end

   def update
     @item = Item.find(params[:id])
     @item.name = params[:item][:name]

     if @item.save
       flash[:notice] = "Item was updated."
       redirect_to user_path(current_user)
     else
       flash.now[:alert] = "There was an error saving the item. Please try again."
       render :edit
     end
   end

   def destroy

   @item = Item.find(params[:id])
   if @item.destroy
     flash[:notice] = "\"#{@item.name}\" was deleted successfully."
      #redirect_to user_path(current_user)
   else
     flash.now[:alert] = "There was an error deleting the item."
     #redirect_to user_path(current_user)
   end
   respond_to do |format|
    format.html
    format.js
  end
 end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
end

def create
  user = User.find_by(email: params[:session][:email].downcase)

  if user && user.authenticate(params[:session][:password])
    create_session(user)
    flash[:notice] = "Welcome, #{user.name}!"
    redirect_to user_path(current_user)
  else
    flash.now[:alert] = 'Invalid email/password combination'
    render :new
  end
end

def destroy
  destroy_session(current_user)
  flash[:notice] = "You've been signed out, come back soon!"
  redirect_to root_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
   end

  def show
    @user = User.find(params[:id])
    @items = @user.items.all

  end

  def create
    @user = User.new
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      flash[:notice] = "Welcome to Bloccit #{@user.name}!"
      create_session(@user)
      redirect_to user_path(current_user)
    else
      flash.now[:alert] = 'There was an error creating your account. Please try again.'
      render :new
    end
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create_session(user)
    session[:user_id] = user.id
  end

  def destroy_session(user)
    session[:user_id] = nil
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
 <div class="row">
      <%= form_for [user, item] do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter item" %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
 </div>

app/views/items/_item.html.erb
<div class="media" id="item-<%= item.id %>">
  <div class="media-body">
    <h4 class="media-heading">
      <%=  item.name %>
      <%= link_to "", [item.user, item], method: :delete, class: 'glyphicon glyphicon-ok', remote: true %>
    </h4>
    <small>
      Time remaining: <%= distance_of_time_in_words(Time.now, item.created_at + 7.days) %>
    </small>
  </div>
</div>

app/views/items/create.js.erb
<% if @item.valid? %>
  $('.js-items').prepend("<%= escape_javascript(render(@item)) %>");
$('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: { user: @user, item: @new_item }) %>");
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
  $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: { user: @user, item: @item }) %>");
<% end %>

app/views/items/destroy.js.erb
 $('#item-<%= @item.id %>').hide();

 <% if @item.destroyed? %>
   $('#item-<%= @item.id %>').hide();
 <% else %>
   $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      
      <div class="pull-right user-info">
        <% if current_user %>
           <%= current_user.name %> - <%= link_to "Sign Out", session_path(current_user), method: :delete %>
         <% else %>
           <%= link_to "Sign In", new_session_path %> or
           <%= link_to "Sign Up", new_user_path %>
         <% end %>
      </div>
    </ul>

    <%= yield %>
  </div>

</body>
</html>

app/views/users/new.html.erb
<h2>Sign up</h2>

 <div class="row">
   <div class="col-md-8">
     <%= form_for @user do |f| %>
       <% if @user.errors.any? %>
         <div class="alert alert-danger">
           <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
           <ul>
             <% @user.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
       <% end %>
 <div class="field">
   <%= f.label :name %><br />
   <%= f.text_field :name %>
 </div>
 <div class="field">
   <%= f.label :email %><br />
   <%= f.email_field :email %>
 </div>
 <div class="field">
   <%= f.label :password %>
   <% if @minimum_password_length %>
   <em>(<%= @minimum_password_length %> characters minimum)</em>
   <% end %><br />
   <%= f.password_field :password, autocomplete: "off" %>
 </div>
 <div class="field">
   <%= f.label :password_confirmation %><br />
   <%= f.password_field :password_confirmation, autocomplete: "off" %>
 </div>

 <div class="actions">
   <%= f.submit "Sign up" %>
 </div>
 <% end %>

app/views/users/show.html.erb
 <h2>To Do</h2>
 <!-- <div class='js-items-count'><%= pluralize(@user.items.count, 'item') %></div> -->
 <%= render @user.items %>
 <h2>New Item</h2>
<%= render 'items/form', item: Item.new, user: @user %>

app/views/welcome/index.html.erb
<br>
<br>
 <div class="jumbotron">
   <h1>Blocitoff</h1>
   <p>Bloccitoff is a self destructing to-do list!</p>
   <p>
     <%= link_to "Sign In", new_session_path %> or
     <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
   </p>
 </div>

 <div class="row">
   <div class="col-md-4">
     <h2>Keep lists manageable</h2>
     <p>Keeps to-do lists to only your most important tasks.</p>
   </div>
   <div class="col-md-4">
     <h2>Self Destructing</h2>
     <p>Don't let your to-do list accumulate junk.  Let Blocitoff destroy old items for you.<p>
   </div>
   <div class="col-md-4">
     <h2>Keep life simple</h2>
     <p>Blocitoff keeps your life simple and organized.</p>
   </div>
 </div>